### ISSUE TITLE
mvn clean leaves booster submodule in dirty state

### ISSUE THREAD

**Issue by dwightguth** [runtimeverification/hs-backend-booster#250]
If you check out the frontend repo, run `mvn clean`, then run `git status`, you will see this:

```
On branch develop
Your branch is up to date with 'origin/develop'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
        modified:   hs-backend-booster/src/main/native/hs-backend-booster (modified content)

no changes added to commit (use "git add" and/or "git commit -a")
```

If you cd into the submodule you can see that this is what was modified:

```
HEAD detached at a258fe8
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   stack.yaml.lock

no changes added to commit (use "git add" and/or "git commit -a")
```

We're running the same command in the haskell backend, but this doesn't happen. Whatever was done there to prevent this from happening needs to be done to the booster too.

**Comment by jberthold** [comment]
Thanks for pointing this out. 
This was caused by the automation that upgrades the haskell-backend dependency in `hs-backend-booster`. The ugprade job in CI was not checking in the modified `stack.yaml.lock`  so `stack.yaml.lock` was inconsistent after an automatic upgrade. I will fix the upgrade job and after the next dependency upgrade in the K repo we will have a consistent submodule again
