### ISSUE TITLE
Clarify the meaning and use of `substitution` in the execute response

### ISSUE THREAD

**Issue by jberthold** [runtimeverification/hs-backend-booster#290]
The `substitution` filed of `ExecuteResponse` is returned by Kore when we fall-back to it in Booster. The substitution returned by Kore seems to be "informational", i.e. the variables will already have been substituted in the term. We, however, conjunct the substitution to the term when returning from Booster. This is likely unsound, since we add constraints on variables that are not present in the configuration anymore.

**Comment by geo2a** [comment]
Upon executing a rule with an ensures clause, the following behavior will be observed:

## `booster-dev`

The substitution will not be applied to the configuration. The ensured constraint will be returned in `predicate` as `CONSTRAINT #Equasl true`.

The same behavior will be exhibited by `kore-rpc-booster` if it does not fall-back to Kore. If it does fall-back the behavior will be as described below for `kore-rpc-dev`.

## `kore-rpc-dev`

The substitution **will** be applied to the configuration. The ensured constraint will be returned in `substutition` as `CONSTRAINT`.

Now, this behavior seems as desired if the substitution is *symbolic*, i.e., for example, we learn that `X ==Int Y`. We then substitute `X` for `Y` in the configuration, this eliminating `X`, but retain the information about this equality and return it as `substitution`. However, if we learn that, for example, `X ==Int 42`, we perform the same operation: substitute and return the *concrete* substitution. While this behavior of the backend is consistent, we need to scream very loudly at `pyk` about it, since it seems that blindly `#And`ing the substitution returned by `kore-rpc`/`kore-rpc-booster` to a configuration may easily result in under-approximation, i.e. we may end-up with a state transition like `<int> X </int>` => `<int> 42 </int> #And (X #Equals 42)`.

See https://github.com/runtimeverification/hs-backend-booster/pull/291 for the integration tests that illustrate these behaviors.
