### ISSUE TITLE
Create `kore-rpc-differ`: a tool to check parity of `kore-rpc-*` server responses

### ISSUE THREAD

**Issue by geo2a** [runtimeverification/hs-backend-booster#325]
This tool should call kore-rpc and booster on requests in a bug report and compare for response parity via internal data structures. this way we should avoid pointless encoding differences between the JSON responses and have a much more detailed diffing, e.g. do configs differ or only some side conditions?

**Comment by goodlyrottenapple** [comment]
I think the idea to re-run requests instead of trying to match was to make it easier to identify diverging behaviors. if you get two bug reports with different no. of responses, we would just fail and not produce a very useful error. however, if you run the requests with both, you may find that we e.g. abort early half-way through request x in booster and we should report that point as a place to investigate...
