### ISSUE TITLE
Support multiple clients in parallel

### ISSUE THREAD

**Issue by nwatson22** [runtimeverification/hs-backend-booster#383]
Currently the `kore-rpc-booster` server is able to handle clients connecting to it and making requests from different processes, but at some point there is a bottleneck where only one connection at a time can make progress, preventing any speedup from using multiple clients to make independent requests in parallel to one server. From what I understood, there are at least 2 issues to be dealt with for this limitation to be overcome: opening multiple z3 processes, and the fact that the servers contain state from `add_module`, because of which @tothtamas28 had said we might consider different ways of handling the modules that get used in the other request types, e.g. sessions or cookies.

**Comment by tothtamas28** [comment]
We should also consider sending structured data as opposed to KORE text like `add-module` does currently. This might as well be implemented in a new endpoint to avoid a breaking change.

Example for "session with internal ID":

Request:

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "add-rules",
  "params": {
    "rules": [
      ["<rule0_lhs>", "<rule0_rhs>"],
      ["<rule1_lhs>", "<rule1_rhs>"],
      "...",
      ["<ruleN_lhs>", "<ruleN_rhs>"]
    ]
  }
}
```

Response:

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "id":  "47d3a45f-8aa3-41f0-9111-2fb940423e9b"
  }
}
```

`execute` and other endpoints take an optional list of rule set IDs:

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "execute",
  "params": {
    "max-depth": 4,
    "...": "...",
    "log-timing": true,
    "rules": ["47d3a45f-8aa3-41f0-9111-2fb940423e9b"]
  }
}
```

**Comment by tothtamas28** [comment]
@dwightguth, @ehildenb, @PetarMax

**Comment by goodlyrottenapple** [comment]
Pool of solvers implementation:
https://github.com/ethereum/hevm/blob/ed79da0df6052b8274677dfe3e02155e4cdf562e/src/EVM/Solvers.hs#L99-L160

**Comment by ehildenb** [comment]
Some notes (mostly covered by Tamas above):

- Different backends will have different restrictions on what they allow in new modules. The Haskell backend may not allow new sorts/syntax, but the Maude backend won't care, for example. So the transport shouldn't care about what the user is sending (only rules, no syntax, etc...), should just allow full modules. Later, we may have uses for declaring new sorts/syntax on the fly as we learn about things during symbolic execution (new constants that are contract specific, etc...).
- A use case for CSE (compositional symbolic execution) will be to create enclosing modules for deeper nested functions (and the rules we learn for them by doing symbolic execution), then import those enclosing modules selectively for proving larger functions. For example, we have two functions `test_1` and `test_2`, where `test_1` calls `g`, `f`, and `h`, and `test_2` calls `g`, `h`, and `i`. Then we want to symbolically execute all of `g`, `f`, `h`, `i`, and make modules `RULES-G`, `RULES-F`, `RULES-H`, `RULES-I`. Then we make `module DEPENDENCIES-TEST-1 imports RULES-G imports RULES-F imports RULE-H endmodule`, and symbolically execute `test_1` in that context. Similarly, we make a module `DEPENDENCIES-TEST-2`, which imports the appropriate sub-modules for executing `test_2` in. So we want modules specifically because they give us _modularity_.
- User may have multiple backends started up, each which they have sent all the modules. Those backends will likely return different unique IDs for the modules they store. So the user will probably have an easier time referring to the module they want to execute in by _name_, rather than by unique ID, in order to dispatch queries to the correct backend. So I think we should at least allow both.

**Comment by goodlyrottenapple** [comment]
https://github.com/runtimeverification/hs-backend-booster/pull/414 and https://github.com/runtimeverification/haskell-backend/pull/3702 implement a very simpler version of concurrent back-ends, which should be safe for multiple clients to connect to without module clashed. This is done by confiding state to the session, which means that every client that connect gets a session where they can add modules and execute within said context. The session is destroyed when the client disconnects. The upside to this is that there is very little change necessary on both the client and server side. THe downside is some possible duplication of add module requests, if the pyk front-end maintains several connections which should all have the same state. 

If this implementation is unsatisfactory and we want to go with the full module IDs proposal, we need to clarify how exactly we distinguish between module names and IDs and will have to modify the kore parser and internalisation procedures, which will be a somewhat more involved change to both code bases.

**Comment by tothtamas28** [comment]
As a simplifying assumption, to avoid modifications in the parser, we can let generated IDs be valid module names for now. We'll probably move from KORE text to JSON in the module filed eventually, we can revisit this assumption then.

Would this make implementation simpler?
