### ISSUE TITLE
Handle `rawTerm` wrapper from the simplifier

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/hs-backend-booster#431]
The LLVM backend has added a new way of handling non-symbol terms across API boundaries; previously when doing so we added a spurious injection into `KItem` to non-symbol terms when returning them to callers. This could be worked around, but was not completely sound.

Clients that call backend binding APIs that use the new `rawTerm` symbol must be aware of it when deserializing or parsing binary or textual KORE. For the Python bindings, the deserialization logic is implemented [here directly in C++.](https://github.com/runtimeverification/llvm-backend/blob/7b6d8526dd6c68e06fb8ef3ffd0d69978928d9bc/include/kllvm/binary/deserializer.h#L276-L281)

The intended semantics are to perform the following rewrite unconditionally during parsing or deserialization:
```
rawTerm{}(inj{S, SortKItem{}}(X)) → X
```
where the sort variable `S` is the real sort of the term `X`.

Blocking: https://github.com/runtimeverification/llvm-backend/pull/931

Related:
* https://github.com/runtimeverification/llvm-backend/pull/907
* https://github.com/runtimeverification/llvm-backend/pull/905

**Comment by Baltoli** [comment]
Further discussion on Slack: https://runtimeverification.slack.com/archives/CC360GUTG/p1702578768476599

**Comment by Baltoli** [comment]
@gtrepta to send some additional context over to @jberthold

**Comment by gtrepta** [comment]
You can reproduce the failure introduced by the `rawTerm` wrapper by doing the following:

- Build K on the latest `develop` branch, but with the `simplify_rawTerm` branch checked out in the llvm-backend submodule (`llvm-backend/src/main/native/llvm-backend`)
- add `k-distribution/bin` to your PATH
- in `hs-backend-booster/src/main/native/hs-backend-booster` run `stack test :llvm-integration`

You can also build with `kup` by doing `kup install k --override llvm-backend 77f6e98`. But, I'm not sure how to run the booster's llvm integration tests with it. I get a glibc linking error when I try it because the interpreter library gets built against the nix environment, and stack tries to use it against the host environment.

**Comment by jberthold** [comment]
Thanks @gtrepta . 
Preparing the booster code in advance means that I have to make two PRs, one to handle the newly returned `rawTerm` value and another to clean up the previous workaround once the LLVM change is present in K master. But that's fine.
