### ISSUE TITLE
Booster falls back to the Haskell backend because of unevaluated functions.

### ISSUE THREAD

**Issue by virgil-serbanuta** [runtimeverification/hs-backend-booster#498]
Versions:
```
$ kompile --version
K version:    v6.1.82-0-g8c99ee7740
Build date:   Vi ian 19 11:28:02 EET 2024
$ kore-rpc-booster --version
hs-backend-booster version:
  revision:     6067fee77da53ac357ce5d17ad34e4639070804a
  branch:       HEAD
  last commit:  Tue Jan 16 09:27:16 2024 -0700
```

Bug report:
[unevaluated-functions.tar.gz](https://github.com/runtimeverification/hs-backend-booster/files/14211022/unevaluated-functions.tar.gz)

Logs:
```
[...]
[Info] Process request 1 execute
[Info#proxy] Starting execute request
[Rewrite] Uncertain about a condition in rule /tmp/kbuild-kmxwasm-semantics-_exg7e37/kmxwasm-semantics/include/kmxwasm-semantics/mx-semantics/vmhooks/bigIntOps.md :  ( 349
, 10 ) :  _andBool_(
    _andBool_(
        _in_keys(_)_MAP_Bool_KItem_Map(
            "4294967195",
            {"4294967282"->"100", "4294967195"->VarARG_0:SortInt{}}
        ),
        isInt(
            kseq(
                _[_]orDefault__MAP_KItem_Map_KItem_KItem(
                    {"4294967282"->"100", "4294967195"->VarARG_0:SortInt{}},
                    "4294967195",
                    "0"
                ),
                dotk()
            )
        )
    ),
    _andBool_(
        _in_keys(_)_MAP_Bool_KItem_Map(
            "4294967282",
            {"4294967282"->"100", "4294967195"->VarARG_0:SortInt{}}
        ),
        isInt(
            kseq(
                _[_]orDefault__MAP_KItem_Map_KItem_KItem(
                    {"4294967282"->"100", "4294967195"->VarARG_0:SortInt{}},
                    "4294967282",
                    "0"
                ),
                dotk()
            )
        )
    )
) @(hs-backend-booster-0.0.0-qJEsy50ZKtfpZmzEpvni:Booster.Pattern.Rewrite library/Booster/Pattern/Rewrite.hs:616:18)
[Rewrite] Applied simplification @(hs-backend-booster-0.0.0-qJEsy50ZKtfpZmzEpvni:Booster.Pattern.Rewrite library/Booster/Pattern/Rewrite.hs:616:18)
[Rewrite] Aborted after 0 steps. @(hs-backend-booster-0.0.0-qJEsy50ZKtfpZmzEpvni:Booster.Pattern.Rewrite library/Booster/Pattern/Rewrite.hs:616:18)
[Info#proxy] Booster Aborted at Depth {getNat = 0}
[Info#proxy] Simplifying booster state and falling back to Kore 
[...]
```

**Comment by jberthold** [comment]
Thanks a lot for preparing the bug report with a single focussed request!
I have inspected the logs and rules in the provided `definition.kore` to find out what exactly blocks the evaluation here.

Please note that `kore-rpc-booster` does not implement its own "hooked functions". It will use the LLVM backend library for fully-concrete expressions and try equations/simplifications given in the K definition otherwise, or ultimately fall back to the legacy backend (as we see here).

To understand the inability to evaluate the condition, let's look at the `isInt(kseq(_[_]orDefault_...( <map>, "42949672..", "0"), .K)` part of the expressions
1. The part `_[_]orDefault_...( <map>, "42949672..", "0")` contains a map with concrete keys but a variable in one of the associated values. Therefore the evaluation cannot (at least _does_ not) use the LLVM backend.
2. There is a simplification rule in `ceils.k:415` that would rewrite `_[_]orDefault_(M, K, _) => Map:lookup(M, K)` if `K in_keys(M)`. However 
   - The rule RHS contains a partial function so it would need to be marked with `preserves-definedness`.
   - The rule uses a `concrete()` attribute so it won't be applied to a map containing a symbolic value (even though only the keys matter here)
 3. Let's assume we would be rewriting the term to `Map:lookup(M, K)`. This is still a hooked function that would be evaluated using the LLVM backend if the map was fully-concrete. 
 4. Ultimately, we would want to instead apply _rules for symbolic lookup_ ([with](https://github.com/runtimeverification/k/blob/1e4aa2be6b49ca766e01d78eae0e418a749bb12b/k-distribution/include/kframework/builtin/domains.md?plain=1#L437-L438) or [without default](https://github.com/runtimeverification/k/blob/1e4aa2be6b49ca766e01d78eae0e418a749bb12b/k-distribution/include/kframework/builtin/domains.md?plain=1#L432-L433), see `domains.md`). Alas, these rules may operate on an undefined LHS (in case of a duplicate key) and are therefore avoided by `kore-rpc-booster`. These rules could be marked with `preserves-definedness` because the `ensures` clause indeed "preserves" the undefined LHS case on the RHS.
 5. Once the rules are marked in this way, the matcher in `kore-rpc-booster` must be modified to allow matching maps with non-concrete _values_ (while still requiring concrete _keys_ ), or even allow matching non-concrete but syntactically identical key expressions. The unifier (for rewriting) already does that but the matcher  currently won't match any non-concrete maps.
