### ISSUE TITLE
Unify code with legacy backend

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/hs-backend-booster#532]
As part of https://github.com/runtimeverification/k/issues/4063, we've been thinking about how best we can begin to rationalise the dependency graph of the various components of K. If we can cut down the number of edges in this graph, then the number of places where something can go wrong (e.g. during a dependency update, or when making changes to the language as we've been doing recently) is minimised.

One such simplification that came out of the discussion was to merge the legacy and booster codebases into one larger project. Doing so has a few benefits that present themselves immediately off the top of my head:
- One fewer dependency update step that can fail in the current dependency chain
- Simpler CI for projects that use the Haskell backend; there's a long-standing observation that the legacy code ends up getting built twice when we build the booster.
- Simpler issue management
- Easier integration should we decide to go "full monorepo" after following the lightweight process in https://github.com/runtimeverification/k/issues/4063#issuecomment-1971457051

However, I'm well aware that this might not be a trivial thing to implement; I'm not a Haskell developer and I'm not familiar enough with the tooling to make an informed technical decision here. It would be great to hear from the team about how viable this might be to do in the medium term, and if there are substantial obstacles in the way of us doing so.

**Comment by jberthold** [comment]
We have discussed merging the two repositories in the team previously, and I don't see any major blockers to doing so. 
Building the actual code is easy because the two repositories are well-aligned wrt. dependencies and build tools.
The biggest work to achieve the desired merge would be to align the testing and convenience tools: 
* Integration Test setup: `haskell-backend` has a larger testing surface because of its different entry points. However, we can just keep its `make`-based test setup, confined in its own directory.
* Formatting and linting: both tools use the same formatter and code analysis but their configuration and usage might need to be aligned. This will cause some fall-out in terms of formatting changes but no major issues.

**Comment by jberthold** [comment]
Useful: How to merge repositories without losing history: https://stackoverflow.com/a/10548919 and https://gist.github.com/x-yuri/9890ab1079cf4357d6f269d073fd9731

**Comment by Baltoli** [comment]
Great; that's pleasing to hear - I agree that we should just merge the two directly to start with; then subsequently work on cleaning up the two integration test setups (we'll be doing similar with Pyk / the krun tests in the frontend, so we may well be able to align that work).

**Comment by jberthold** [comment]
Work has started on this. Status:
- Plan is to merge `hs-backend-booster` into `haskell-backend` (into a subdirectory) to get 4 Haskell packages in subdirectories at the end.
- Currently blocked on https://github.com/runtimeverification/hs-backend-booster/pull/534 (needs K dependency versions aligned in both repositories)

**Comment by jberthold** [comment]
Preparing a scripted merge in branch https://github.com/runtimeverification/haskell-backend/compare/jb/merge-prep
